name: notion-backup-docker-workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # will be triggered at 04:05 on every 2nd day-of-month from 2 through 30.
  schedule:
    - cron: '5 4 2-30/2 * *'

# See https://github.com/marketplace/actions/docker-run-step
# See https://github.com/addnab/docker-run-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kohlerdominik/docker-run-action@v1
        with:
          # public, private or local image
          image: jckleiner/notion-backup
          # pass or create environment variables
          environment: |
            NOTION_SPACE_ID=${{ secrets.NOTION_SPACE_ID }}
            NOTION_EMAIL=${{ secrets.NOTION_EMAIL }}
            NOTION_PASSWORD=${{ secrets.NOTION_PASSWORD }}
            
            GOOGLE_DRIVE_ROOT_FOLDER_ID=${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER_ID }}
            GOOGLE_DRIVE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}
            GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON=${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON }}
            GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH=${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH }}
            
            DROPBOX_ACCESS_TOKEN=${{ secrets.DROPBOX_ACCESS_TOKEN }}
            
            NEXTCLOUD_EMAIL=${{ secrets.NEXTCLOUD_EMAIL }}
            NEXTCLOUD_PASSWORD=${{ secrets.NEXTCLOUD_PASSWORD }}
            NEXTCLOUD_WEBDAV_URL=${{ secrets.NEXTCLOUD_WEBDAV_URL }}

          # run is required: "Error: Input required and not supplied: run"
          run: |
            echo "hello world"
            uname -a



